name: GitHub Actions Demo
on:
  push:
    branches:
      -main
    branches-ignore: 
      -'.github/**'
  pull_request:
    branches: 
      -main
  schedule:
    - cron: 15 6 * * 0


jobs:
  initialize_repo:
    runs-on: ubuntu-latest
  
   

   
  
  

  
    
